# flake8: noqa
# Generated by Django 3.2.4 on 2021-06-07 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('event', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0003_auto_20210607_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportthrough',
            name='evend_id',
        ),
        migrations.AddField(
            model_name='supportthrough',
            name='event_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='event.event'),
        ),
        migrations.AlterField(
            model_name='salerthrough',
            name='client_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.client'),
        ),
        migrations.AlterField(
            model_name='salerthrough',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='supportthrough',
            name='client_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.client'),
        ),
        migrations.AlterField(
            model_name='supportthrough',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
